services:
  trading-bot:
    build: ./bot
    container_name: trading-bot
    env_file: .env
    restart: unless-stopped
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./bot:/app
    command: ["bash", "-lc", "uvicorn app.main:app --host ${API_BIND:-0.0.0.0} --port 8000"]
  ml-worker:
    build: ./bot
    container_name: ml-worker
    env_file: .env
    volumes:
      - ./bot:/app
    command: ["python", "-m", "app.ml_worker"]