version: "3.8"

services:
  trading-bot:
    build: ./bot
    container_name: trading-bot
    env_file: .env
    restart: unless-stopped
    networks:
      - default
    ports:
      - "${API_PORT:-8080}:8080"
    volumes:
      - ./bot:/app
    command: [ "bash", "-lc", "uvicorn app.main:app --host ${API_BIND:-0.0.0.0} --port 8080" ]

networks:
  default:
    driver: bridge
